version: '3.9'

services:
  postgres:
    container_name: authentication-service-database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-authentication_service}
      POSTGRES_PORT: ${POSTGRES_PORT:-8241}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8241:5432"
    restart: unless-stopped

volumes:
  postgres:
